# Sample context from the file
context = """
IN THE CONTEXT FILE, ALL LOOK-AND-FEEL SPECIFICATIONS ARE DEFINED BY THE LOOKANDFEEL ELEMENT UNDER CUSTOMSEARCHENGINE. THIS ELEMENT DETERMINES WHETHER ADS ARE DISPLAYED, HOW THE SEARCH RESULTS SECTION ARE RENDERED, AND HOW INDIVIDUAL SEARCH RESULTS ARE DISPLAYED. THE FOLLOWING EXAMPLE SHOWS ALL THE ATTRIBUTES AND CHILD ELEMENTS OF THE LOOKANDFEEL ELEMENT.
THIS PAGE DESCRIBES HOW TO CUSTOMIZE THE APPEARANCE OF YOUR SEARCH ENGINE USING THE CONTEXT FILE, WHICH IS THE XML SPECIFICATION FOR YOUR SEARCH ENGINE.
THE RESULTS ELEMENT CONTROLS THE COLOR OF INDIVIDUAL RESULTS IN THE SEARCH ELEMENT. EACH INDIVIDUAL RESULT FORMS A UNIT OF TITLE, RESULT SNIPPET, AND LINK. DEFINING THIS CHILD ELEMENT LETS YOU VISUALLY DELINEATE INDIVIDUAL RESULTS OR HIGHLIGHT RESULTS THAT ARE BEING SELECTED BY USERS.
THIS ELEMENT CONTROLS THE COLOR FOR THE INDIVIDUAL RESULTS.
"""

# Specify the text to search for
search_text = "FILE"

# Find the index of the search text
index = context.find(search_text)

if index != -1:
    print(f'Text found at index: {index}')
else:
    print('Text not found.')
